### PR TITLE
fix: configuration get config

### PR DESCRIPTION
**Pull request by fdymylja**
solves: https://github.com/iov-one/iovns/issues/227

### CODE REVIEW

**Comment by fdymylja** [comment]
NOTE: whilst during store handling this is not an issue, amino complains if we try to unmarshal jsons which contain integers (this is why instead of using the codec in CLI functions we use iovns.DefaultQueryEncode/Decode). I don't know if we should address this since amino support is getting dropped soon, and it would require some annoying refactoring to do.

Cc @davepuchyr @orkunkl

**Comment by fdymylja** [comment]
NOTE 2:

ATM we're using two types which mirror the same thing.
here: https://github.com/iov-one/iovns/pull/228/files#diff-8465702dc905a99a0f5a64f93ce721dfR4
and here: https://github.com/iov-one/iovns/blob/master/x/configuration/query.go#L99

same goes for query fees

this can get hard to maintain in the long term, the extra type (which lays in configuration/types) cannot be removed due to import cycling. so we can either move the queries and the config keeper in the keeper pkg to avoid cycling, or we can use the type.QueryResponse but this would create an inconsistent API compared to what we have in domain module.

Your call.

**Comment by davepuchyr** [comment]
> NOTE: whilst during store handling this is not an issue, amino complains if we try to unmarshal jsons which contain integers (this is why instead of using the codec in CLI functions we use iovns.DefaultQueryEncode/Decode). I don't know if we should address this since amino support is getting dropped soon, and it would require some annoying refactoring to do.
> 
> Cc @davepuchyr @orkunkl

Let's defer the annoying refactoring until it's forced upon us.

**Comment by davepuchyr** [comment]
> NOTE 2:
> 
> ATM we're using two types which mirror the same thing.
> here: https://github.com/iov-one/iovns/pull/228/files#diff-8465702dc905a99a0f5a64f93ce721dfR4
> and here: https://github.com/iov-one/iovns/blob/master/x/configuration/query.go#L99
> 
> same goes for query fees
> 
> this can get hard to maintain in the long term, the extra type (which lays in configuration/types) cannot be removed due to import cycling. so we can either move the queries and the config keeper in the keeper pkg to avoid cycling, or we can use the type.QueryResponse but this would create an inconsistent API compared to what we have in domain module.
> 
> Your call.

Let's discuss this in Slack.

**Pull request merged**
