### PR TITLE
Update to cosmos-sdk v0.39.1

### PR DESCRIPTION
**Pull request by alessio**

### CODE REVIEW

**Comment by alessio** [comment]
Please ensure that the exported genesis file is migrated before restarting the node.

**Comment by davepuchyr** [comment]
> Please ensure that the exported genesis file is migrated before restarting the node.

Thanks, @alessio.  Will do.

**Comment by fdymylja** [comment]
lgtm

**Comment by davepuchyr** [comment]
@alessio , just FYI, our CI that includes integration tests is [green](https://github.com/iov-one/iovns/pull/292/checks) with v0.39-rc1, but note that we're still using https://github.com/iov-one/iovns/blob/master/go.mod#L29, which is/was relevant for multisig accounts.

**Comment by davepuchyr** [comment]
> @alessio , just FYI, our CI that includes integration tests is [green](https://github.com/iov-one/iovns/pull/292/checks) with v0.39-rc1, but note that we're still using https://github.com/iov-one/iovns/blob/master/go.mod#L29, which is/was relevant for multisig accounts.

We successfully [dropped the bech32 patch](https://github.com/iov-one/iovns/pull/297).

**Comment by alessio** [comment]
@davepuchyr dixit:

> We successfully dropped the bech32 patch.

Splendid! Did you manage to migrate the state too?

**Comment by davepuchyr** [comment]
> Splendid! Did you manage to migrate the state too?

No, we're starting completely from scratch since we're dropping Weave SDK in favor of Cosmos SDK.

**Pull request merged**
