### PR TITLE
Fee module

### PR DESCRIPTION
**Pull request by orkunkl**

### CODE REVIEW

**Comment by orkunkl** [comment]
Naturally, there are import cycle errors: 
```
package github.com/iov-one/iovns/cmd/iovnscli
        imports github.com/iov-one/iovns/app
        imports github.com/iov-one/iovns/x/domain
        imports github.com/iov-one/iovns/x/domain/client/cli
        imports github.com/iov-one/iovns/x/domain/keeper
        imports github.com/iov-one/iovns/x/fee/calculator
        imports github.com/iov-one/iovns/x/domain
```
Its caused by hardcoded domain messages in fees:
```go
type Fees struct {
	// FeeCoinDenom defines the denominator of the coin used to process fees
	FeeCoinDenom string  `json:"fee_coin_denom"`
	FeeCoinPrice sdk.Dec `json:"fee_coin_price"`
...

Before taking action I wanted to ask your ideas @fdymylja

**Comment by fdymylja** [comment]
Of course there are, I'll express my opinion on this, I don't think fees should be tightly coupled with the domain module (or any module of any kind), I think the sdk.Msg implemented by our types should produce a unique identifier for the fee which is then mapped in our fee model. So the Fee, per se, should be a map. This makes cosmos sdk mad because maps cannot be deterministically marshalled, but there's a workaround for this, you can use the MustSortJSON function to achieve determinism on json marshalled maps. Since the fee object is just one we don't need the amino codec performance and zipping of objects bytes.

So we can just json.Marshal the map which maps->
sdk.Msg.UniqueIdentifier-> sdk.Coin

and after that MusrtSortJSON on the produced marshalled bytes.

This should be better in my opinion.

and the collect fee works in this way, it accepts an sdk.Msg from which it produces a unique identifier string which then is used to get the sdk.Coin fee from the map.


On a secondary note, the CLI docs will require updates.

cc @davepuchyr @BenSim

**Comment by davepuchyr** [comment]
To me, fees should be embeded in `config`, eg
```
"configuration": {
  "config": {
    "fees": {
...
```
I realize the counter argument to that is that there might be some fees that aren't related to `config`.  However, since we're 100% focused on providing a name service, I doubt that that will be the case.  Nonetheless, if the consensus is for `fees` to not be part of `config` or there's a technical reason why it can't be then `fees` should have it's own `configurer`.

**Comment by davepuchyr** [comment]
> On a secondary note, the CLI docs will require updates.

Let's be consistent with the input methodologies for `update-fees` and `update-config`; see https://github.com/iov-one/iovns/issues/237.

**Comment by orkunkl** [comment]
With the design I want to propose couple changes.
First one: Fee seed term. 
Fee seed is the values in the kv store that will be used to formulate a fee from a message.
Here is an example msg fee calculation method:
```golang
func (m *MsgRegisterDomain) CalculateFee(calculator FeeCalculator) (sdk.Dec, error) {
	var seedID string
	level := len(calculator.domain.Name)
	switch level {
	case 1,2,3,4,5,6:
		seedID = snakeCaseAppend(m.Type(), string(level))
	default:
		seedID = snakeCaseAppend(m.Type(), "default")
	}

	feeSeed := calculator.k.FeeKeeper.GetFeeSeed(calculator.ctx, seedID)
	var fee sdk.Dec
	// if domain is open then we multiply
	if calculator.domain.Type == OpenDomain {
		multiplier := calculator.k.FeeKeeper.GetFeeSeed(calculator.ctx, "register_open_domain_multiplier")
		fee = sdk.Dec(feeSeed).Mul(sdk.Dec(multiplier))
	}
	return fee, nil
}
```
Calculator is implemented on the domain module level. It keeps account/domain instances and domain keeper. 
```golang
type FeeCalculator struct {
	fee.Calculator
	account *Account
	domain  *Domain

	ctx sdk.Context
	k   keeper.Keeper
}
```
And I introduced Collector interface in fee module:
```golang
func NewCollector(k Keeper) Collector {
	return Collector{
		k: k,
	}
}

func (gc Collector) CollectFee(ctx sdk.Context, fee sdk.Coin, addr sdk.AccAddress) error {
	return gc.k.CollectFee(ctx, fee, addr)
}
```
Collector instances is created when app is launched and injected into modules. This behaviour is same as keepers.

**Pull request closed without merging**
